version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/app'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'app'

  - package-ecosystem: 'pip'
    directory: '/hapi'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'hapi'
