version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/app'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'app'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'pip'
    directory: '/hapi'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'hapi'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
