name: hapi

on:
  push:
    branches: [main]
    paths:
      - 'hapi/**'
      - '.github/workflows/hapi.yml'
  pull_request:
    branches: [main]
    paths:
      - 'hapi/**'
      - '.github/workflows/hapi.yml'
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hapi
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create Zappa config
        run: |
          cat > zappa_settings.json << EOL
          {
            "production": {
              "app_function": "run.app",
              "domain": "${{ secrets.ZAPPA_DOMAIN }}",
              "route53": true,
              "certificate_arn": "${{ secrets.CERTIFICATE_ARN }}",
              "base_path": "",
              "aws_region": "${{ secrets.AWS_REGION }}",
              "exclude": ["boto3", "dateutil", "botocore", "s3transfer", "concurrent"],
              "project_name": "hapi",
              "runtime": "python3.12",
              "s3_bucket": "${{ secrets.S3_BUCKET }}"
            }
          }
          EOL
      - name: Deploy
        run: zappa update production
